name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  ci:
    uses: Volontariapp/ci-tools/.github/workflows/runner-pipeline.yml@main
    with:
      service-name: workers-runners
      services: '["worker-user", "worker-event", "worker-post", "worker-social"]'
    secrets:
      ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
